import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { KeyboardAwareScrollViewCompat } from '@/components/KeyboardAwareScrollViewCompat';
import { LogoMark, PrimaryButton } from '@/components/ShopUI';
import { useShop } from '@/context/ShopContext';
import { useColors } from '@/hooks/useColors';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
export default function LoginScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { user, hydrated, signIn } = useShop();
  const [email, setEmail] = useState('alex@example.com'); const [password, setPassword] = useState('shoptrail'); const [error, setError] = useState('');
  useEffect(() => { if (hydrated && user) router.replace('/(tabs)'); }, [hydrated, user]);
  const handleSignIn = () => { if (!email.includes('@')) { setError('Enter a valid email to continue.'); return; } if (password.length < 4) { setError('Your password needs at least 4 characters.'); return; } signIn({ name: email.split('@')[0].replace(/[._-]/g, ' '), email }); router.replace('/(tabs)'); };
  if (!hydrated) return <View style={[styles.loading, { backgroundColor: colors.background }]}><ActivityIndicator color={colors.primary} /></View>;
  return <KeyboardAwareScrollViewCompat keyboardShouldPersistTaps="handled" bottomOffset={40} style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.container, { paddingTop: insets.top + 26, paddingBottom: insets.bottom + 30 }]}>
    <View style={styles.topRow}><LogoMark /><Text style={[styles.version, { color: colors.mutedForeground }]}>MEMBER ACCESS</Text></View>
    <View style={styles.hero}><View style={[styles.heroOrb, { backgroundColor: colors.secondary }]}><Feather name="arrow-up-right" size={28} color={colors.primary} /></View><Text style={[styles.title, { color: colors.foreground }]}>Your everyday, made more intentional.</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>Curated objects for better routines, delivered with care.</Text></View>
    <View style={styles.form}><Text style={[styles.formLabel, { color: colors.foreground }]}>Sign in to your trail</Text><View style={[styles.inputWrap, { backgroundColor: colors.card, borderColor: error ? colors.destructive : colors.border }]}><Feather name="mail" size={18} color={colors.mutedForeground} /><TextInput value={email} onChangeText={(value) => { setEmail(value); setError(''); }} placeholder="Email address" placeholderTextColor={colors.mutedForeground} autoCapitalize="none" keyboardType="email-address" style={[styles.input, { color: colors.foreground }]} /></View><View style={[styles.inputWrap, { backgroundColor: colors.card, borderColor: error ? colors.destructive : colors.border }]}><Feather name="lock" size={18} color={colors.mutedForeground} /><TextInput value={password} onChangeText={(value) => { setPassword(value); setError(''); }} placeholder="Password" placeholderTextColor={colors.mutedForeground} secureTextEntry style={[styles.input, { color: colors.foreground }]} /></View>{!!error && <Text style={[styles.errorText, { color: colors.destructive }]}>{error}</Text>}<PrimaryButton label="Sign in" icon="arrow-right" onPress={handleSignIn} /><Pressable onPress={() => { setEmail('hello@shoptrail.co'); setPassword('welcome'); signIn({ name: 'hello', email: 'hello@shoptrail.co' }); router.replace('/(tabs)'); }} style={styles.demoButton}><Text style={[styles.demoText, { color: colors.primary }]}>Continue with demo account</Text></Pressable></View>
    <View style={[styles.trustRow, { borderTopColor: colors.border }]}><Feather name="shield" size={16} color={colors.success} /><Text style={[styles.trustText, { color: colors.mutedForeground }]}>A calm, secure place for your saved finds.</Text></View>
  </KeyboardAwareScrollViewCompat>;
}
const styles = StyleSheet.create({ loading: { flex: 1, alignItems: 'center', justifyContent: 'center' }, container: { flexGrow: 1, paddingHorizontal: 22 }, topRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, version: { fontFamily: 'Inter_600SemiBold', fontSize: 9, letterSpacing: 1.3 }, hero: { marginTop: 56, marginBottom: 44 }, heroOrb: { width: 62, height: 62, borderRadius: 24, alignItems: 'center', justifyContent: 'center', marginBottom: 20, transform: [{ rotate: '10deg' }] }, title: { fontFamily: 'Inter_700Bold', fontSize: 33, lineHeight: 39, letterSpacing: -1.2 }, subtitle: { fontFamily: 'Inter_400Regular', fontSize: 15, lineHeight: 23, marginTop: 15, maxWidth: 290 }, form: { gap: 12 }, formLabel: { fontFamily: 'Inter_600SemiBold', fontSize: 15, marginBottom: 2 }, inputWrap: { height: 55, borderRadius: 16, borderWidth: 1, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, gap: 11 }, input: { flex: 1, fontFamily: 'Inter_400Regular', fontSize: 15 }, errorText: { fontFamily: 'Inter_500Medium', fontSize: 12, marginTop: -3 }, demoButton: { alignItems: 'center', paddingVertical: 10 }, demoText: { fontFamily: 'Inter_600SemiBold', fontSize: 13 }, trustRow: { marginTop: 'auto', borderTopWidth: 1, paddingTop: 18, flexDirection: 'row', alignItems: 'center', gap: 8 }, trustText: { fontFamily: 'Inter_400Regular', fontSize: 12 } });
