import { Feather } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { PrimaryButton, LogoMark } from '@/components/ShopUI';
import { useShop } from '@/context/ShopContext';
import { useColors } from '@/hooks/useColors';
 export default function OrderSuccessScreen() { const colors = useColors(); const insets = useSafeAreaInsets(); const { id } = useLocalSearchParams<{ id: string }>(); const { orders } = useShop(); const order = orders.find((item) => item.id === id) || orders[0]; return <View style={[styles.container, { backgroundColor: colors.background, paddingTop: insets.top + 20, paddingBottom: insets.bottom + 20 }]}><LogoMark /><View style={styles.center}><View style={[styles.successIcon, { backgroundColor: colors.secondary }]}><Feather name="check" size={32} color={colors.success} /></View><Text style={[styles.title, { color: colors.foreground }]}>It is on its way to becoming yours.</Text><Text style={[styles.copy, { color: colors.mutedForeground }]}>Thanks for choosing thoughtfully. We have your order and will send updates as it moves.</Text>{order && <View style={[styles.orderCard, { backgroundColor: colors.card }]}><View><Text style={[styles.orderLabel, { color: colors.mutedForeground }]}>ORDER NUMBER</Text><Text style={[styles.orderId, { color: colors.foreground }]}>{order.id}</Text></View><Text style={[styles.orderTotal, { color: colors.foreground }]}>$ {order.total}</Text></View>}</View><View style={styles.actions}><PrimaryButton label="View my orders" icon="package" onPress={() => router.replace('/(tabs)/orders')} /><Pressable onPress={() => router.replace('/(tabs)')} style={styles.continue}><Text style={[styles.continueText, { color: colors.primary }]}>Continue shopping</Text></Pressable></View></View>; }
const styles = StyleSheet.create({ container: { flex: 1, paddingHorizontal: 22 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, successIcon: { width: 82, height: 82, borderRadius: 41, alignItems: 'center', justifyContent: 'center', marginBottom: 25 }, title: { fontFamily: 'Inter_700Bold', fontSize: 29, lineHeight: 33, letterSpacing: -1, textAlign: 'center' }, copy: { fontFamily: 'Inter_400Regular', fontSize: 14, lineHeight: 22, textAlign: 'center', maxWidth: 300, marginTop: 16 }, orderCard: { width: '100%', marginTop: 28, borderRadius: 18, padding: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, orderLabel: { fontFamily: 'Inter_700Bold', fontSize: 9, letterSpacing: 1.5, marginBottom: 6 }, orderId: { fontFamily: 'Inter_700Bold', fontSize: 16 }, orderTotal: { fontFamily: 'Inter_700Bold', fontSize: 18 }, actions: { gap: 8 }, continue: { alignItems: 'center', paddingVertical: 14 }, continueText: { fontFamily: 'Inter_600SemiBold', fontSize: 13 } });
