import React from 'react';
import { Platform, StyleSheet, useColorScheme, View } from 'react-native';
import { useColors } from '@/hooks/useColors';
import { Feather } from '@expo/vector-icons';
import { BlurView } from 'expo-blur';
import { isLiquidGlassAvailable } from 'expo-glass-effect';
import { Tabs } from 'expo-router';
import { Icon, Label, NativeTabs } from 'expo-router/unstable-native-tabs';
import { SymbolView } from 'expo-symbols';
function NativeTabLayout() { return <NativeTabs><NativeTabs.Trigger name="index"><Icon sf={{ default: 'house', selected: 'house.fill' }} /><Label>Home</Label></NativeTabs.Trigger><NativeTabs.Trigger name="search"><Icon sf="magnifyingglass" /><Label>Search</Label></NativeTabs.Trigger><NativeTabs.Trigger name="bag"><Icon sf={{ default: 'bag', selected: 'bag.fill' }} /><Label>Bag</Label></NativeTabs.Trigger><NativeTabs.Trigger name="orders"><Icon sf={{ default: 'shippingbox', selected: 'shippingbox.fill' }} /><Label>Orders</Label></NativeTabs.Trigger><NativeTabs.Trigger name="account"><Icon sf={{ default: 'person', selected: 'person.fill' }} /><Label>Account</Label></NativeTabs.Trigger></NativeTabs>; }
function ClassicTabLayout() { const colors = useColors(); const colorScheme = useColorScheme(); const isDark = colorScheme === 'dark'; const isIOS = Platform.OS === 'ios'; const isWeb = Platform.OS === 'web'; return <Tabs screenOptions={{ headerShown: false, tabBarActiveTintColor: colors.primary, tabBarInactiveTintColor: colors.mutedForeground, tabBarStyle: { position: 'absolute', backgroundColor: isIOS ? 'transparent' : colors.background, borderTopWidth: isWeb ? 1 : 0, borderTopColor: colors.border, elevation: 0, height: isWeb ? 84 : 64, paddingTop: 7, paddingBottom: isWeb ? 34 : 7 }, tabBarLabelStyle: { fontFamily: 'Inter_500Medium', fontSize: 10 }, tabBarBackground: () => isIOS ? <BlurView intensity={100} tint={isDark ? 'dark' : 'light'} style={StyleSheet.absoluteFill} /> : isWeb ? <View style={[StyleSheet.absoluteFill, { backgroundColor: colors.background }]} /> : null }}><Tabs.Screen name="index" options={{ title: 'Home', tabBarIcon: ({ color }) => isIOS ? <SymbolView name="house" tintColor={color} size={23} /> : <Feather name="home" size={21} color={color} /> }} /><Tabs.Screen name="search" options={{ title: 'Search', tabBarIcon: ({ color }) => <Feather name="search" size={21} color={color} /> }} /><Tabs.Screen name="bag" options={{ title: 'Bag', tabBarIcon: ({ color }) => <Feather name="shopping-bag" size={21} color={color} /> }} /><Tabs.Screen name="orders" options={{ title: 'Orders', tabBarIcon: ({ color }) => <Feather name="package" size={21} color={color} /> }} /><Tabs.Screen name="account" options={{ title: 'Account', tabBarIcon: ({ color }) => <Feather name="user" size={21} color={color} /> }} /></Tabs>; }
export default function TabLayout() { return isLiquidGlassAvailable() ? <NativeTabLayout /> : <ClassicTabLayout />; }
