import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useMemo, useState } from 'react';
import { Image, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { categories, products } from '@/data/catalog';
import { useShop } from '@/context/ShopContext';
import { IconButton, LogoMark, ProductCard, SectionHeader } from '@/components/ShopUI';
import { useColors } from '@/hooks/useColors';
import { useHaptics } from '@/hooks/useHaptics';
export default function HomeScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { user, cartCount, addToCart } = useShop(); const [selectedCategory, setSelectedCategory] = useState('All'); const [refreshing, setRefreshing] = useState(false); const { tap, success } = useHaptics();
  const filtered = useMemo(() => selectedCategory === 'All' ? products : products.filter((product) => product.category === selectedCategory), [selectedCategory]); const firstName = user?.name.split(' ')[0] || 'there'; const handleAdd = (product: (typeof products)[number]) => { addToCart(product); success(); };
  return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.content, { paddingTop: insets.top + 15, paddingBottom: insets.bottom + 90 }]} showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); setTimeout(() => setRefreshing(false), 600); }} tintColor={colors.primary} />}>
    <View style={styles.header}><LogoMark /><IconButton name="shopping-bag" badge={cartCount} onPress={() => router.push('/(tabs)/bag')} accessibilityLabel="Open shopping bag" /></View>
    <View style={styles.greeting}><Text style={[styles.eyebrow, { color: colors.primary }]}>GOOD MORNING</Text><Text style={[styles.title, { color: colors.foreground }]}>Find a little more joy, {firstName}.</Text></View>
    <Pressable onPress={() => router.push('/(tabs)/search')} style={({ pressed }) => [styles.heroCard, { backgroundColor: colors.foreground }, pressed && { opacity: 0.94 }]}><View style={styles.heroCopy}><Text style={[styles.heroEyebrow, { color: colors.accent }]}>THE NEW EDIT</Text><Text style={[styles.heroTitle, { color: colors.background }]}>Small things. Big feeling.</Text><Text style={[styles.heroDescription, { color: colors.background }]}>Objects that make everyday rituals feel like yours.</Text><View style={[styles.heroCta, { backgroundColor: colors.background }]}><Text style={[styles.heroCtaText, { color: colors.foreground }]}>Explore now</Text><Feather name="arrow-up-right" size={16} color={colors.foreground} /></View></View><View style={[styles.heroShape, { backgroundColor: colors.primary }]}><View style={[styles.heroShapeInner, { backgroundColor: colors.accent }]} /></View></Pressable>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.categoryRow} style={styles.categoryScroll}>{categories.map((category) => { const active = selectedCategory === category.label; return <Pressable key={category.label} onPress={() => { tap(); setSelectedCategory(category.label); }} style={[styles.categoryPill, { backgroundColor: active ? colors.foreground : colors.card, borderColor: active ? colors.foreground : colors.border }]}><Feather name={category.icon as keyof typeof Feather.glyphMap} size={15} color={active ? colors.background : colors.mutedForeground} /><Text style={[styles.categoryLabel, { color: active ? colors.background : colors.foreground }]}>{category.label}</Text></Pressable>; })}</ScrollView>
    <SectionHeader title={selectedCategory === 'All' ? 'Made for your space' : selectedCategory} action="See all" onAction={() => router.push('/(tabs)/search')} />
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.productRow}><View style={styles.productPair}>{filtered.slice(0, 2).map((product) => <ProductCard key={product.id} product={product} onPress={() => router.push({ pathname: '/product/[id]', params: { id: product.id } })} onAdd={() => handleAdd(product)} />)}</View>{filtered.length > 2 && <View style={styles.productPair}>{filtered.slice(2, 4).map((product) => <ProductCard key={product.id} product={product} onPress={() => router.push({ pathname: '/product/[id]', params: { id: product.id } })} onAdd={() => handleAdd(product)} />)}</View>}</ScrollView>
    <SectionHeader title="Just landed" action="View all" onAction={() => router.push('/(tabs)/search')} />
     <View style={[styles.featuredCard, { backgroundColor: colors.foreground }]}><Image source={products[1].image} style={styles.featuredImage} /><View style={styles.featuredOverlay}><Text style={[styles.featuredLabel, { color: colors.background }]}>SLOW LIVING</Text><Text style={[styles.featuredTitle, { color: colors.background }]}>Make room for the good stuff.</Text><Pressable onPress={() => router.push({ pathname: '/product/[id]', params: { id: products[1].id } })}><Text style={[styles.featuredLink, { color: colors.accent }]}>Shop the edit  ↗</Text></Pressable></View></View>
  </ScrollView>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 20 }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, greeting: { marginTop: 31, marginBottom: 23 }, eyebrow: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.8, marginBottom: 8 }, title: { fontFamily: 'Inter_700Bold', fontSize: 30, lineHeight: 34, letterSpacing: -1 }, heroCard: { height: 205, borderRadius: 25, overflow: 'hidden', padding: 20, marginBottom: 22, position: 'relative' }, heroCopy: { zIndex: 2, maxWidth: 200 }, heroEyebrow: { fontFamily: 'Inter_700Bold', fontSize: 9, letterSpacing: 1.6, marginBottom: 10 }, heroTitle: { fontFamily: 'Inter_700Bold', fontSize: 25, lineHeight: 26, letterSpacing: -0.7 }, heroDescription: { fontFamily: 'Inter_400Regular', fontSize: 11, lineHeight: 16, opacity: 0.78, marginTop: 10, width: 175 }, heroCta: { borderRadius: 14, paddingVertical: 10, paddingHorizontal: 12, alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 14 }, heroCtaText: { fontFamily: 'Inter_600SemiBold', fontSize: 11 }, heroShape: { position: 'absolute', right: -28, top: 22, width: 182, height: 182, borderRadius: 91, alignItems: 'center', justifyContent: 'center', opacity: 0.94 }, heroShapeInner: { width: 95, height: 95, borderRadius: 48 }, categoryScroll: { marginHorizontal: -20, marginBottom: 25 }, categoryRow: { gap: 8, paddingHorizontal: 20 }, categoryPill: { height: 39, paddingHorizontal: 14, borderRadius: 20, borderWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 7 }, categoryLabel: { fontFamily: 'Inter_500Medium', fontSize: 12 }, productRow: { gap: 12, marginHorizontal: -20, paddingHorizontal: 20, paddingBottom: 28 }, productPair: { flexDirection: 'row', gap: 12 }, featuredCard: { height: 220, borderRadius: 24, overflow: 'hidden', marginBottom: 20 }, featuredImage: { width: '100%', height: '100%', opacity: 0.42 }, featuredOverlay: { position: 'absolute', left: 19, right: 19, top: 20, bottom: 20, justifyContent: 'space-between' }, featuredLabel: { fontFamily: 'Inter_700Bold', fontSize: 9, letterSpacing: 1.7 }, featuredTitle: { fontFamily: 'Inter_700Bold', fontSize: 25, lineHeight: 28, letterSpacing: -0.7 }, featuredLink: { fontFamily: 'Inter_600SemiBold', fontSize: 13 } });
