import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useMemo, useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { categories, products } from '@/data/catalog';
import { ProductCard } from '@/components/ShopUI';
import { useShop } from '@/context/ShopContext';
import { useColors } from '@/hooks/useColors';
import { useHaptics } from '@/hooks/useHaptics';
export default function SearchScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { addToCart } = useShop(); const { success } = useHaptics(); const [query, setQuery] = useState(''); const [category, setCategory] = useState('All');
  const filtered = useMemo(() => products.filter((product) => (category === 'All' || product.category === category) && (product.name.toLowerCase().includes(query.toLowerCase()) || product.description.toLowerCase().includes(query.toLowerCase()))), [category, query]);
  return <KeyboardAvoidingView style={{ flex: 1, backgroundColor: colors.background }} behavior="padding" keyboardVerticalOffset={0}><ScrollView keyboardDismissMode="interactive" style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.content, { paddingTop: insets.top + 15, paddingBottom: insets.bottom + 90 }]}><Text style={[styles.kicker, { color: colors.primary }]}>THE SHOP</Text><Text style={[styles.title, { color: colors.foreground }]}>Find your next favorite thing.</Text><View style={[styles.searchBox, { backgroundColor: colors.card, borderColor: colors.border }]}><Feather name="search" size={19} color={colors.mutedForeground} /><TextInput value={query} onChangeText={setQuery} placeholder="Search objects, rituals, gifts..." placeholderTextColor={colors.mutedForeground} style={[styles.searchInput, { color: colors.foreground }]} returnKeyType="search" /></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{categories.map((item) => { const active = category === item.label; return <Pressable key={item.label} onPress={() => setCategory(item.label)} style={[styles.chip, { backgroundColor: active ? colors.primary : colors.card, borderColor: active ? colors.primary : colors.border }]}><Text style={[styles.chipText, { color: active ? colors.primaryForeground : colors.foreground }]}>{item.label}</Text></Pressable>; })}</ScrollView><View style={styles.resultHeader}><Text style={[styles.resultCount, { color: colors.mutedForeground }]}>{filtered.length} pieces to discover</Text><Feather name="sliders" size={17} color={colors.foreground} /></View><View style={styles.grid}>{filtered.map((product) => <ProductCard key={product.id} product={product} onPress={() => router.push({ pathname: '/product/[id]', params: { id: product.id } })} onAdd={() => { addToCart(product); success(); }} />)}</View>{!filtered.length && <View style={styles.noResults}><Feather name="search" size={28} color={colors.primary} /><Text style={[styles.noResultsTitle, { color: colors.foreground }]}>Nothing matched that search</Text><Text style={[styles.noResultsText, { color: colors.mutedForeground }]}>Try a broader phrase or explore another category.</Text></View>}</ScrollView></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 20 }, kicker: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.8, marginTop: 13, marginBottom: 8 }, title: { fontFamily: 'Inter_700Bold', fontSize: 30, lineHeight: 34, letterSpacing: -1 }, searchBox: { height: 54, borderWidth: 1, borderRadius: 17, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 15, marginTop: 25 }, searchInput: { flex: 1, fontFamily: 'Inter_400Regular', fontSize: 14 }, chips: { gap: 8, paddingVertical: 19 }, chip: { borderWidth: 1, borderRadius: 18, paddingHorizontal: 14, paddingVertical: 9 }, chipText: { fontFamily: 'Inter_500Medium', fontSize: 12 }, resultHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 }, resultCount: { fontFamily: 'Inter_500Medium', fontSize: 12 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, noResults: { alignItems: 'center', paddingVertical: 70, paddingHorizontal: 30 }, noResultsTitle: { fontFamily: 'Inter_700Bold', fontSize: 18, marginTop: 14, marginBottom: 7 }, noResultsText: { fontFamily: 'Inter_400Regular', fontSize: 13, textAlign: 'center', lineHeight: 20 } });
