import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { EmptyState, PrimaryButton } from '@/components/ShopUI';
import { useShop } from '@/context/ShopContext';
import { useColors } from '@/hooks/useColors';
export default function BagScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { cart, cartTotal, updateQuantity, removeFromCart } = useShop(); const shipping = cartTotal >= 100 ? 0 : 8;
  return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.content, { paddingTop: insets.top + 18, paddingBottom: insets.bottom + 94 }]} showsVerticalScrollIndicator={false}><View style={styles.header}><View><Text style={[styles.kicker, { color: colors.primary }]}>YOUR EDIT</Text><Text style={[styles.title, { color: colors.foreground }]}>Shopping bag</Text></View><Text style={[styles.count, { color: colors.mutedForeground }]}>{cart.length} {cart.length === 1 ? 'item' : 'items'}</Text></View>{!cart.length ? <><EmptyState icon="shopping-bag" title="Your bag is waiting" message="Add something beautiful to your bag and it will show up here." /><PrimaryButton label="Explore the shop" icon="arrow-right" onPress={() => router.push('/(tabs)/search')} /></> : <><View style={styles.items}>{cart.map((item) => <View key={item.product.id} style={[styles.item, { backgroundColor: colors.card }]}><Image source={item.product.image} style={[styles.itemImage, { backgroundColor: item.product.accent }]} /><View style={styles.itemInfo}><Text style={[styles.itemCategory, { color: colors.mutedForeground }]}>{item.product.category}</Text><Text style={[styles.itemName, { color: colors.foreground }]}>{item.product.name}</Text><Text style={[styles.itemPrice, { color: colors.foreground }]}>$ {item.product.price}</Text><View style={styles.itemBottom}><View style={[styles.stepper, { borderColor: colors.border }]}><Pressable onPress={() => updateQuantity(item.product.id, item.quantity - 1)} hitSlop={8}><Feather name="minus" size={14} color={colors.foreground} /></Pressable><Text style={[styles.qty, { color: colors.foreground }]}>{item.quantity}</Text><Pressable onPress={() => updateQuantity(item.product.id, item.quantity + 1)} hitSlop={8}><Feather name="plus" size={14} color={colors.foreground} /></Pressable></View><Pressable onPress={() => removeFromCart(item.product.id)} hitSlop={8}><Feather name="trash-2" size={16} color={colors.mutedForeground} /></Pressable></View></View></View>)}</View><View style={[styles.summary, { borderTopColor: colors.border }]}><View style={styles.summaryRow}><Text style={[styles.summaryLabel, { color: colors.mutedForeground }]}>Subtotal</Text><Text style={[styles.summaryValue, { color: colors.foreground }]}>$ {cartTotal}</Text></View><View style={styles.summaryRow}><Text style={[styles.summaryLabel, { color: colors.mutedForeground }]}>Delivery</Text><Text style={[styles.summaryValue, { color: shipping === 0 ? colors.success : colors.foreground }]}>{shipping === 0 ? 'Free' : '$ ' + shipping}</Text></View><View style={styles.summaryRow}><Text style={[styles.totalLabel, { color: colors.foreground }]}>Total</Text><Text style={[styles.totalValue, { color: colors.foreground }]}>$ {cartTotal + shipping}</Text></View><PrimaryButton label="Continue to checkout" icon="arrow-right" onPress={() => router.push('/checkout')} /></View></>}</ScrollView>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 20 }, header: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', marginBottom: 27 }, kicker: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.8, marginBottom: 8 }, title: { fontFamily: 'Inter_700Bold', fontSize: 30, letterSpacing: -1 }, count: { fontFamily: 'Inter_500Medium', fontSize: 12, marginBottom: 3 }, items: { gap: 12 }, item: { borderRadius: 20, padding: 12, flexDirection: 'row', gap: 13 }, itemImage: { width: 95, height: 115, borderRadius: 14 }, itemInfo: { flex: 1, paddingVertical: 2 }, itemCategory: { fontFamily: 'Inter_600SemiBold', fontSize: 9, letterSpacing: 1, textTransform: 'uppercase', marginBottom: 6 }, itemName: { fontFamily: 'Inter_600SemiBold', fontSize: 15, marginBottom: 7 }, itemPrice: { fontFamily: 'Inter_700Bold', fontSize: 14 }, itemBottom: { marginTop: 'auto', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, stepper: { borderWidth: 1, borderRadius: 12, height: 31, paddingHorizontal: 9, flexDirection: 'row', alignItems: 'center', gap: 12 }, qty: { fontFamily: 'Inter_600SemiBold', fontSize: 13 }, summary: { borderTopWidth: 1, marginTop: 28, paddingTop: 20, gap: 14 }, summaryRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, summaryLabel: { fontFamily: 'Inter_400Regular', fontSize: 14 }, summaryValue: { fontFamily: 'Inter_500Medium', fontSize: 14 }, totalLabel: { fontFamily: 'Inter_700Bold', fontSize: 18 }, totalValue: { fontFamily: 'Inter_700Bold', fontSize: 22 } });
