import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { EmptyState, PrimaryButton } from '@/components/ShopUI';
import { useShop } from '@/context/ShopContext';
import { useColors } from '@/hooks/useColors';
export default function OrdersScreen() { const colors = useColors(); const insets = useSafeAreaInsets(); const { orders } = useShop(); return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.content, { paddingTop: insets.top + 18, paddingBottom: insets.bottom + 94 }]}><Text style={[styles.kicker, { color: colors.primary }]}>YOUR TRAIL</Text><Text style={[styles.title, { color: colors.foreground }]}>Orders</Text>{!orders.length ? <><EmptyState icon="package" title="No orders yet" message="When you find something that feels like you, your order will live here." /><PrimaryButton label="Start exploring" icon="arrow-right" onPress={() => router.push('/(tabs)/search')} /></> : <View style={styles.list}>{orders.map((order) => <Pressable key={order.id} onPress={() => router.push({ pathname: '/order-success', params: { id: order.id } })} style={[styles.orderCard, { backgroundColor: colors.card }]}><View style={styles.orderHeader}><View><Text style={[styles.orderId, { color: colors.foreground }]}>{order.id}</Text><Text style={[styles.date, { color: colors.mutedForeground }]}>{new Date(order.createdAt).toLocaleDateString('en-CA', { month: 'short', day: 'numeric', year: 'numeric' })}</Text></View><View style={[styles.status, { backgroundColor: order.status === 'Delivered' ? colors.secondary : colors.muted }]}><View style={[styles.statusDot, { backgroundColor: order.status === 'Delivered' ? colors.success : colors.primary }]} /><Text style={[styles.statusText, { color: colors.foreground }]}>{order.status}</Text></View></View><View style={[styles.orderLine, { backgroundColor: colors.border }]} /><View style={styles.orderBottom}><Text style={[styles.itemSummary, { color: colors.mutedForeground }]}>{order.items.length} {order.items.length === 1 ? 'piece' : 'pieces'} · {order.items[0]?.product.name || 'Shoptrail edit'}</Text><Text style={[styles.orderTotal, { color: colors.foreground }]}>$ {order.total}</Text><Feather name="chevron-right" size={17} color={colors.mutedForeground} /></View></Pressable>)}</View>}</ScrollView>; }
const styles = StyleSheet.create({ content: { paddingHorizontal: 20 }, kicker: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.8, marginTop: 13, marginBottom: 8 }, title: { fontFamily: 'Inter_700Bold', fontSize: 30, letterSpacing: -1, marginBottom: 27 }, list: { gap: 12 }, orderCard: { borderRadius: 20, padding: 16 }, orderHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' }, orderId: { fontFamily: 'Inter_700Bold', fontSize: 15, marginBottom: 5 }, date: { fontFamily: 'Inter_400Regular', fontSize: 12 }, status: { flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 12, paddingHorizontal: 9, paddingVertical: 7 }, statusDot: { width: 6, height: 6, borderRadius: 3 }, statusText: { fontFamily: 'Inter_600SemiBold', fontSize: 10 }, orderLine: { height: 1, marginVertical: 16 }, orderBottom: { flexDirection: 'row', alignItems: 'center', gap: 8 }, itemSummary: { flex: 1, fontFamily: 'Inter_400Regular', fontSize: 12 }, orderTotal: { fontFamily: 'Inter_700Bold', fontSize: 14 } });
