import { Feather } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import React from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { PrimaryButton, Stars } from '@/components/ShopUI';
import { getProduct } from '@/data/catalog';
import { useShop } from '@/context/ShopContext';
import { useColors } from '@/hooks/useColors';
import { useHaptics } from '@/hooks/useHaptics';
export default function ProductScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { id } = useLocalSearchParams<{ id: string }>(); const product = getProduct(id || ''); const { addToCart } = useShop(); const { success } = useHaptics();
  if (!product) return <View style={[styles.notFound, { backgroundColor: colors.background }]}><Text style={[styles.notFoundTitle, { color: colors.foreground }]}>That piece has moved on.</Text><Pressable onPress={() => router.back()}><Text style={[styles.backLink, { color: colors.primary }]}>Go back</Text></Pressable></View>;
  return <View style={{ flex: 1, backgroundColor: colors.background }}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: insets.bottom + 105 }}><View style={[styles.imageWrap, { backgroundColor: product.accent }]}><Image source={product.image} style={styles.heroImage} resizeMode="cover" /><Pressable onPress={() => router.back()} style={[styles.backButton, { backgroundColor: colors.background }]}><Feather name="arrow-left" size={19} color={colors.foreground} /></Pressable><Pressable style={[styles.favoriteButton, { backgroundColor: colors.background }]}><Feather name="heart" size={19} color={colors.foreground} /></Pressable></View><View style={styles.detail}><View style={styles.detailTop}><View><Text style={[styles.category, { color: colors.primary }]}>{product.category.toUpperCase()}</Text><Text style={[styles.name, { color: colors.foreground }]}>{product.name}</Text></View><Text style={[styles.price, { color: colors.foreground }]}>$ {product.price}</Text></View><Stars rating={product.rating} reviews={product.reviews} /><Text style={[styles.description, { color: colors.mutedForeground }]}>{product.description}</Text><View style={[styles.divider, { backgroundColor: colors.border }]} /><Text style={[styles.sectionTitle, { color: colors.foreground }]}>The details</Text><View style={styles.details}>{product.details.map((detail) => <View key={detail} style={styles.detailRow}><View style={[styles.detailDot, { backgroundColor: colors.primary }]} /><Text style={[styles.detailText, { color: colors.foreground }]}>{detail}</Text></View>)}</View><View style={[styles.shippingCard, { backgroundColor: colors.secondary }]}><Feather name="truck" size={18} color={colors.foreground} /><View style={styles.shippingCopy}><Text style={[styles.shippingTitle, { color: colors.foreground }]}>Free delivery over $100</Text><Text style={[styles.shippingText, { color: colors.mutedForeground }]}>Ships in 1–2 business days</Text></View></View></View></ScrollView><View style={[styles.bottomBar, { backgroundColor: colors.background, borderTopColor: colors.border, paddingBottom: insets.bottom + 12 }]}><PrimaryButton label="Add to bag" icon="shopping-bag" onPress={() => { addToCart(product); success(); }} /></View></View>;
}
const styles = StyleSheet.create({ imageWrap: { height: 390, position: 'relative' }, heroImage: { width: '100%', height: '100%' }, backButton: { position: 'absolute', top: 56, left: 20, width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' }, favoriteButton: { position: 'absolute', top: 56, right: 20, width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' }, detail: { padding: 22 }, detailTop: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 10 }, category: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.8, marginBottom: 8 }, name: { fontFamily: 'Inter_700Bold', fontSize: 27, letterSpacing: -0.8, maxWidth: 220 }, price: { fontFamily: 'Inter_700Bold', fontSize: 21, marginTop: 16 }, description: { fontFamily: 'Inter_400Regular', fontSize: 15, lineHeight: 23, marginTop: 21 }, divider: { height: 1, marginVertical: 25 }, sectionTitle: { fontFamily: 'Inter_700Bold', fontSize: 17, marginBottom: 15 }, details: { gap: 12 }, detailRow: { flexDirection: 'row', alignItems: 'center', gap: 11 }, detailDot: { width: 7, height: 7, borderRadius: 4 }, detailText: { fontFamily: 'Inter_500Medium', fontSize: 14 }, shippingCard: { borderRadius: 17, padding: 15, flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 28 }, shippingCopy: { gap: 3 }, shippingTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 13 }, shippingText: { fontFamily: 'Inter_400Regular', fontSize: 12 }, bottomBar: { position: 'absolute', left: 0, right: 0, bottom: 0, borderTopWidth: 1, paddingHorizontal: 20, paddingTop: 12 }, notFound: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 25 }, notFoundTitle: { fontFamily: 'Inter_700Bold', fontSize: 21, marginBottom: 10 }, backLink: { fontFamily: 'Inter_600SemiBold', fontSize: 14 } });
