import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { LogoMark } from '@/components/ShopUI';
import { useShop } from '@/context/ShopContext';
import { useColors } from '@/hooks/useColors';
 export default function AccountScreen() { const colors = useColors(); const insets = useSafeAreaInsets(); const { user, orders, signOut } = useShop(); const rows = [{ icon: 'package', label: 'Order history', detail: orders.length + ' ' + (orders.length === 1 ? 'order' : 'orders'), onPress: () => router.push('/(tabs)/orders') }, { icon: 'map-pin', label: 'Saved address', detail: 'Add your first address', onPress: () => Alert.alert('Saved address', 'Your saved address will be available for faster checkout.') }, { icon: 'help-circle', label: 'Need a hand?', detail: 'We are here for you', onPress: () => Alert.alert('We are here for you', 'Send a note to hello@shoptrail.co and our team will reply soon.') }]; return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.content, { paddingTop: insets.top + 18, paddingBottom: insets.bottom + 94 }]}><View style={styles.header}><LogoMark compact /><Text style={[styles.kicker, { color: colors.primary }]}>YOUR SPACE</Text></View><View style={styles.profile}><View style={[styles.avatar, { backgroundColor: colors.primary }]}><Text style={[styles.avatarText, { color: colors.primaryForeground }]}>{(user?.name || 'A').charAt(0).toUpperCase()}</Text></View><View><Text style={[styles.name, { color: colors.foreground }]}>{user?.name || 'Shoptrail member'}</Text><Text style={[styles.email, { color: colors.mutedForeground }]}>{user?.email || 'hello@shoptrail.co'}</Text></View></View><View style={[styles.memberCard, { backgroundColor: colors.foreground }]}><View><Text style={[styles.memberKicker, { color: colors.accent }]}>SHOPTRAIL MEMBER</Text><Text style={[styles.memberTitle, { color: colors.background }]}>Good things take time.</Text></View><Feather name="heart" size={26} color={colors.primary} /></View><View style={styles.rows}>{rows.map((row) => <Pressable key={row.label} onPress={row.onPress} style={({ pressed }) => [styles.row, { backgroundColor: colors.card }, pressed && { opacity: 0.75 }]}><View style={[styles.rowIcon, { backgroundColor: colors.muted }]}><Feather name={row.icon as keyof typeof Feather.glyphMap} size={18} color={colors.foreground} /></View><View style={styles.rowText}><Text style={[styles.rowLabel, { color: colors.foreground }]}>{row.label}</Text><Text style={[styles.rowDetail, { color: colors.mutedForeground }]}>{row.detail}</Text></View><Feather name="chevron-right" size={17} color={colors.mutedForeground} /></Pressable>)}</View><Pressable onPress={() => { signOut(); router.replace('/'); }} style={styles.signOut}><Feather name="log-out" size={16} color={colors.destructive} /><Text style={[styles.signOutText, { color: colors.destructive }]}>Sign out</Text></Pressable><Text style={[styles.footer, { color: colors.mutedForeground }]}>SHOPTRAIL · MADE FOR THE EVERYDAY</Text></ScrollView>; }
const styles = StyleSheet.create({ content: { paddingHorizontal: 20 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 28 }, kicker: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.8 }, profile: { flexDirection: 'row', alignItems: 'center', gap: 13, marginBottom: 25 }, avatar: { width: 54, height: 54, borderRadius: 27, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontFamily: 'Inter_700Bold', fontSize: 21 }, name: { fontFamily: 'Inter_700Bold', fontSize: 19, marginBottom: 5 }, email: { fontFamily: 'Inter_400Regular', fontSize: 13 }, memberCard: { minHeight: 154, borderRadius: 22, padding: 20, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 24 }, memberKicker: { fontFamily: 'Inter_700Bold', fontSize: 9, letterSpacing: 1.6, marginBottom: 14 }, memberTitle: { fontFamily: 'Inter_700Bold', fontSize: 25, lineHeight: 27, letterSpacing: -0.7 }, rows: { gap: 10 }, row: { borderRadius: 17, minHeight: 70, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 12 }, rowIcon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, rowText: { flex: 1, gap: 4 }, rowLabel: { fontFamily: 'Inter_600SemiBold', fontSize: 14 }, rowDetail: { fontFamily: 'Inter_400Regular', fontSize: 12 }, signOut: { flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', paddingVertical: 26 }, signOutText: { fontFamily: 'Inter_600SemiBold', fontSize: 13 }, footer: { fontFamily: 'Inter_600SemiBold', fontSize: 9, textAlign: 'center', letterSpacing: 1.4 } });
